# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-22 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.ManyToManyField(to='mentoring.Mentor'),
        ),
    ]
